services:
  payment-service:
    image: python:3.12-slim
    container_name: payment-service
    volumes:
      - ./services/payment_service:/app
    working_dir: /app
    command: sh -c "pip install fastapi uvicorn requests && uvicorn main:app --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
  accounting-service:
    image: python:3.12-slim
    container_name: accounting-service
    volumes:
      - ./services/accounting_service:/app
    working_dir: /app
    command: sh -c "pip install fastapi uvicorn && uvicorn main:app --host 0.0.0.0 --port 8001"
    ports:
      - "8001:8001"
